import Head from "next/head";
import { useState } from "react";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillLinkedin } from "react-icons/ai";
import {
	SiReact,
	SiHtml5,
	SiCss3,
	SiTailwindcss,
	SiJavascript,
	SiNextdotjs,
	SiNodedotjs,
	SiExpress,
	SiFirebase,
	SiMongodb,
	SiDocker,
	SiPostgresql,
	SiGit,
	SiGithub,
} from "react-icons/si";
import Image from "next/image";
import memoji from "../public/memoji.png";
import computer from "../public/computer.png";
import code from "../public/code.png";
import database from "../public/database.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
	const [darkMode, setDarkMode] = useState(false);

	return (
		<div className={darkMode ? "dark" : ""}>
			<Head>
				<title>Greg Vermaak Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
				<section className="min-h-screen">
					<nav className="py-10 mb-12 flex justify-between dark:text-white">
						<h1 className="text-xl font-Burtons">dev greg</h1>
						<ul className="flex items-center">
							<li>
								<BsFillMoonStarsFill
									onClick={() => setDarkMode(!darkMode)}
									className="cursor-pointer text-2xl"
								/>
							</li>
							<li>
								<a
									className="bg-gradient-to-b from-emerald-500 to-emerald-600 text-white px-4 py-2 rounded-md ml-8"
									href="https://docs.google.com/document/d/1dtxUSWEwS8OYWl2kkcodQ9NGT8HkZZQ-hP3smy6ew-E/edit?usp=sharing"
									target="_blank"
									rel="noopener noreferrer"
								>
									Resume
								</a>
							</li>
						</ul>
					</nav>
					<div className="text-center p-10">
						<h2 className="text-5xl py-2 text-emerald-600 font-medium dark:text-teal-400 md:text-6xl">
							Greg Vermaak
						</h2>
						<h3 className="text-2xl py-2 dark:text-white md:text-3xl">
							Full Stack Developer.
						</h3>
						<p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
							Full Stack dev driven by passion. Hailing all the way from New
							Zealand!
						</p>
					</div>
					<div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
						<a
							href="https://github.com/gregvermaak"
							target="_blank"
							rel="noopener noreferrer"
						>
							<AiFillGithub />
						</a>
						<a
							href="https://www.linkedin.com/in/gregvermaak/"
							target="_blank"
							rel="noopener noreferrer"
						>
							<AiFillLinkedin />
						</a>
					</div>
					<div className="relative mx-auto bg-gradient-to-b from-emerald-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
						<Image
							alt="portfolio"
							src={memoji}
							layout="fill"
							objectFit="cover"
						/>
					</div>
				</section>
				{/* Experience Section */}
				<section>
					<div>
						<h3 className="text-3xl py-1 dark:text-white">About Me</h3>
						<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
							My name is Greg, I am a Full Stack dev from New Zealand. I create
							bespoke websites to help people go further online.
						</p>
						<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
							Since the beginning of my journey as a developer, I&apos;ve done
							remote work for
							<span className="text-teal-500"> record labels </span>
							and <span className="text-teal-500">startups </span>
							and collaborated with talanted people to create digital products
							for both business and consumer use.
						</p>
					</div>
					<div className="lg:flex gap-10">
						<div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
							<Image alt="portfolio" src={computer} width={100} height={100} />
							<h3 className="text-lg font-medium pt-8 pb-2">Client Side</h3>
							<h4 className="py-4 text-teal-600">Tools I Use</h4>
							<div className="flex items-center justify-around text-5xl mt-6">
								<p className="text-gray-800 py-1">
									<SiHtml5 />
								</p>
								<p className="text-gray-800 py-1">
									<SiCss3 />
								</p>
								<p className="text-gray-800 py-1">
									<SiTailwindcss />
								</p>
								<p className="text-gray-800 py-1">
									<SiJavascript />
								</p>
								<p className="text-gray-800 py-1">
									<SiReact />
								</p>
								<p className="text-gray-800 py-1">
									<SiNextdotjs />
								</p>
							</div>
						</div>
						<div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
							<Image alt="portfolio" src={code} width={100} height={100} />
							<h3 className="text-lg font-medium pt-8 pb-2">Server Side</h3>
							<h4 className="py-4 text-teal-600">Tools I Use</h4>
							<div className="flex items-center justify-around text-5xl mt-6">
								<p className="text-gray-800 py-1">
									<SiNodedotjs />
								</p>
								<p className="text-gray-800 py-1">
									<SiExpress />
								</p>
								<p className="text-gray-800 py-1">
									<SiFirebase />
								</p>
							</div>
						</div>
						<div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
							<Image alt="portfolio" src={database} width={100} height={100} />
							<h3 className="text-lg font-medium pt-8 pb-2 ">
								Databases & Miscellaneous
							</h3>
							<h4 className="py-4 text-teal-600">Tools I Use</h4>
							<div className="flex items-center justify-around text-5xl mt-6">
								<p className="text-gray-800 py-1">
									<SiMongodb />
								</p>
								<p className="text-gray-800 py-1">
									<SiPostgresql />
								</p>
								<p className="text-gray-800 py-1">
									<SiFirebase />
								</p>
								<p className="text-gray-800 py-1">
									<SiDocker />
								</p>
								<p className="text-gray-800 py-1">
									<SiGit />
								</p>
							</div>
						</div>
					</div>
				</section>
				<section className="py-10">
					<div>
						<h3 className="text-3xl py-1 dark:text-white ">Portfolio</h3>

						<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
							Below are some of the pieces that I am most proud of. Ranging from
							personal projects to client work.
						</p>
					</div>
					<div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
						<div className="basis-1/3 flex-1 ">
							<Image
								alt="portfolio"
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout="responsive"
								src={web1}
							/>
						</div>
						<div className="basis-1/3 flex-1">
							<Image
								alt="portfolio"
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout="responsive"
								src={web2}
							/>
						</div>
						<div className="basis-1/3 flex-1">
							<Image
								alt="portfolio"
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout="responsive"
								src={web3}
							/>
						</div>
						<div className="basis-1/3 flex-1">
							<Image
								alt="portfolio"
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout="responsive"
								src={web4}
							/>
						</div>
						<div className="basis-1/3 flex-1">
							<Image
								alt="portfolio"
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout="responsive"
								src={web5}
							/>
						</div>
						<div className="basis-1/3 flex-1">
							<Image
								alt="portfolio"
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout="responsive"
								src={web6}
							/>
						</div>
					</div>
				</section>
			</main>
		</div>
	);
}
